#!/bin/bash
set -e
eval "$($(dirname $0)/adr-config)"

type=$("$adr_bin_dir/_adr_type")

case $type in
    "")
    head -1 $("$adr_bin_dir/_adr_file" "$1") | cut -c 3-
    ;;
    madr)
    grep "^# " $("$adr_bin_dir/_adr_file" "$1") | cut -c 3-
    ;;
esac
